userprofile/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('change_password/', views.MyPasswordChangeView.as_view(), name='change_password'),
    path('edit_username/', views.edit_username, name='edit_username'),
    path('myaccount/delete_account/', views.delete_account, name='delete_account'),
    path('apply-for-vendor/', views.apply_for_vendor, name='apply_for_vendor'),
    path('my_services/', views.my_services, name='my_services'),
    path('my_servics/add_service/', views.add_service, name='add_service'),
    path('my_services/edit_service/<int:pk>/', views.edit_service, name='edit_service'),
    path('my_services/delete_service/<int:pk>/', views.delete_service, name='delete_service'),
    path('vendors/<int:pk>/', views.vendor_detail, name='vendor_detail'),
]

webshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import handler404

from core.views import frontpage, about, custom_404

handler404 = 'core.views.custom_404'

urlpatterns = [
    path('about/', about, name='about'),
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('', include('userprofile.urls')),
    path('', include('storefront.urls')),
    path('', frontpage, name='frontpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storefront/models.py
from statistics import mode
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.db.models import Avg
from django.core.files import File
from django.core.validators import MinValueValidator, MaxValueValidator

from io import BytesIO
from PIL import Image
from django.utils import timezone

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class District(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    class Meta:
        verbose_name_plural = 'Districts'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Service(models.Model):
    DRAFT = 'draft'
    WAITING_APPROVAL = 'waitingapproval'
    ACTIVE = 'active'
    DELETED = 'deleted'

    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    user = models.ForeignKey(User, related_name='services', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', related_name='services', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    description = models.TextField(blank=True)
    district = models.ForeignKey('District', related_name='services', on_delete=models.CASCADE, null=True, blank=True)
    precise_location = models.CharField(max_length=50, default='this area')
    image = models.ImageField(upload_to='uploads/service_images', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='uploads/service_images/thumbnail', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)
    phone_number = models.CharField(max_length=20, default='1234567890')
    whatsapp_number = models.CharField(max_length=20, default='1234567890')
    email = models.EmailField(default='example@example.com')

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        elif self.image:
            self.thumbnail = self.make_thumbnail(self.image)
            self.save()
            return self.thumbnail.url
        else:
            return 'https://via.placeholder.com/240x240x.jpg'

    def average_rating(self):
        # Calculate average rating of associated reviews
        return self.reviews.aggregate(avg_rating=Avg('rating'))['avg_rating']


class Review(models.Model):
    service = models.ForeignKey('Service', related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    comment = models.TextField()

    class Meta:
        unique_together = ('service', 'user')  # Ensure one review per user per service

    def __str__(self):
        return f'Review by {self.user.username} for {self.service.title}'

class Appointment(models.Model):
    PENDING = 'Pending'
    ACCEPTED = 'Accepted'
    DENIED = 'Denied'

    STATUS_CHOICES = (
        (PENDING , 'Pending'),
        (ACCEPTED, 'Accepted'),
        (DENIED, 'Denied')
    )
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    time = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=PENDING)

    def __str__(self):
        if self.service:
            return f"{self.service.title} - {self.time}"
        return "service"

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User


class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    is_vendor = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

userprofile/views.py
from django.contrib import messages
from django.contrib.auth import login,logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.text import slugify

from .models import Userprofile

from storefront.forms import ServiceForm, VendorApplicationForm, VendorConfirmationForm
from storefront.models import Service, Category


def apply_for_vendor(request):
    if request.method == 'POST':
        form = VendorConfirmationForm(request.POST)
        if form.is_valid():
            confirmation = form.cleaned_data.get('confirmation')
            if confirmation == 'yes':
                request.user.userprofile.is_vendor = True
                request.user.userprofile.save()
                return redirect('my_services')
            else:
                return redirect('myaccount')  # Redirect to "My Account" page with different message
    else:
        form = VendorConfirmationForm()
    return render(request, 'userprofile/vendor_confirmation.html', {'form': form})


def confirm_vendor_application(request):
    if request.method == 'POST':
        form = VendorConfirmationForm(request.POST)
        if form.is_valid():
            confirmation = form.cleaned_data.get('confirmation')
            if confirmation == 'yes':
                request.user.userprofile.is_vendor = True
                request.user.userprofile.save()
                return redirect('my_services')  # Redirect to "My Account" page with success message
            else:
                return redirect('myaccount')  # Redirect to "My Account" page with different message
    else:
        form = VendorConfirmationForm()
    return render(request, 'vendor_confirmation.html', {'form': form})

def vendor_detail(request, pk):
    user = User.objects.get(pk=pk)
    services = user.services.filter(status=Service.ACTIVE)

    return render(request, 'userprofile/vendor_detail.html', {
        'user': user,
        'services': services
    })


@login_required
def my_services(request):
    services = request.user.services.exclude(status=Service.DELETED)

    return render(request, 'userprofile/my_services.html', {
        'services': services
    })


@login_required
def add_service(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES)

        if form.is_valid():
            title = request.POST.get('title')

            service = form.save(commit=False)
            service.user = request.user
            service.slug = slugify(title)
            service.save()

            messages.success(request, 'The service was added.')

            return redirect('my_services')

    else:
        form = ServiceForm()

    return render(request, 'userprofile/service_form.html', {
        'title': 'Add service',
        'form': form
    })


@login_required
def edit_service(request, pk):
    service = Service.objects.filter(user=request.user).get(pk=pk)

    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES, instance=service)

        if form.is_valid():
            form.save()

            messages.success(request, 'The changes have been made.')

            return redirect('my_services')
    else:
        form = ServiceForm(instance=service)

    return render(request, 'userprofile/service_form.html', {
        'title': 'Edit service',
        'service': service,
        'form': form
    })


def delete_service(request, pk):
    service = Service.objects.filter(user=request.user).get(pk=pk)
    service.status = Service.DELETED
    service.save()

    messages.success(request, 'The service was deleted.')

    return redirect('my_services')

@login_required
def myaccount(request):
    return render(request, 'userprofile/myaccount.html')


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            userprofile = Userprofile.objects.create(user=user)
            return redirect('frontpage')

    else:
        form = UserCreationForm()

    # Pass the form.errors dictionary to the template
    return render(request, 'userprofile/signup.html', {
        'form': form,
        'errors': form.errors  # This will include any validation errors in the form
    })


class MyPasswordChangeView(PasswordChangeView):
    template_name = 'myaccount.html'  # Use your template name here
    success_url = reverse_lazy('myaccount')  # Redirect to myaccount on success

    def form_valid(self, form):
        messages.success(self.request, 'Your password was successfully updated.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Failed to update password. Please correct the errors.')
        return super().form_invalid(form)
def edit_username(request):
    if request.method == 'POST':
        new_username = request.POST.get('username')
        user = request.user
        if new_username and new_username != user.username:
            user.username = new_username
            user.save()
            messages.success(request, 'Your username was successfully updated.')
            return redirect('myaccount')
        else:
            messages.error(request, 'Failed to update username. Please try again.')
    return redirect('myaccount')


@login_required
def delete_account(request):
    if request.method == 'POST':
        if 'delete_account' in request.POST:
            request.user.delete()
            logout(request)
            return redirect('frontpage')
        elif 'cancel' in request.POST:
            return redirect('frontpage')     
        
    return render(request, 'userprofile/delete_account.html')
    

userprofile/templates/userprofile/delete_account.html
{% extends 'base.html' %}
{% block title %}Delete Account{% endblock %}
{% block content %}
 <div class="min-h-screen flex flex-col justify-center items-center mt-1">   
<h1 class="text-4xl font-bold mb-4">Delete Account</h1>
    <p class="text-lg mt-2">Are you sure you want to delete your account?</p>
    <form method="post" action="{% url 'delete_account' %}">
        {% csrf_token %}
        <button type="submit" name="delete_account" class="mt-6 inline-block py-4 px-8 bg-red-400 text-white rounded-lg">Yes,delete my account</button>
    </form>

    <form method="post" action="{% url 'frontpage' %}">
        {% csrf_token %}
        <button type="submit" name="cancel" class="mt-6 py-3 px-6 bg-teal-600 text-white rounded-lg">Cancel</button>
    </form>     
 </div>

{% endblock %}

userprofile/templates/userprofile/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

<script src="https://cdn.tailwindcss.com"></script>
    <style>
        /* Additional custom styles */
        .nav-container {
            max-width: 100%;
            padding: 0 1rem;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            align-items: center;
        }
        
        .logo {
            flex: 1; 
        }
    
        .logo a {
            font-size: 1.5rem;
        }
    </style>

{% block content %}
<div class="flex items-center justify-center my-5">
    <img src="\media\uploads\service_images\logo2.png" alt="Service Spotter Logo" class="h-8 mr-2">
    <h1 class="text-2xl font-bold">Service Spotter</h1>
</div>
<div class="max-w-md mt-8 mx-auto bg-white rounded-xl overflow-hidden shadow-md">
    <div class="py-4 px-6">
        <h1 class="text-2xl font-bold mb-4">Login</h1>
        <form method="post" action=".">
            {% csrf_token %}

            {% if form.errors %}
                <div class="mb-4">
                    <p class="text-red-500">Please correct the following errors:</p>
                    <ul>
                        {% for field, error in form.errors.items %}
                            {% for message in error %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <div class="mb-4">
                <label for="id_username" class="block text-sm font-medium text-gray-700">Username:</label>
                <input type="text" name="username" id="id_username" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring focus:ring-teal-500 focus:ring-opacity-50" required autofocus>
            </div>

            <div class="mb-6">
                <label for="id_password" class="block text-sm font-medium text-gray-700">Password:</label>
                <input type="password" name="password" id="id_password" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring focus:ring-teal-500 focus:ring-opacity-50" required>
            </div>

            <div class="mb-6 flex items-center">
                <label for="showPassword" class="flex-grow block text-sm font-medium text-gray-700">Show Passwords:</label>
                <div class="relative">
                    <input type="checkbox" id="showPassword" class="ml-2" onclick="togglePasswordVisibility()">
                </div>
            </div>
            

          
            

            <button type="submit" class="w-full py-2 px-4 bg-teal-600 text-white font-semibold rounded-xl hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-600 focus:ring-opacity-50">Login</button>
        </form>
    </div>
</div>
<script>
    function togglePasswordVisibility() {
        var passwordField = document.getElementById("id_password");
        if (passwordField.type === "password") {
            passwordField.type = "text";
        } else {
            passwordField.type = "password";
        }
    }
    </script>

{% endblock %}
    
</body>
</html>

userprofile/templates/userprofile/my_services.html
{% extends 'base.html' %}

{% block title %}My Services{% endblock %}
<style>
    .service {
        height: auto;
        margin-left: auto;
        margin-right: auto;
    }

    /* Media query for screens smaller than 768px (typical mobile devices) */
    @media (max-width: 767px) {
        .service {
            width: 90%; /* Make the service cards occupy full width */
            height: auto; /* Let the height adjust according to content */
            margin-bottom: 20px; /* Add some spacing between cards */
        }
    }

    .content-container {
        padding-bottom: 60px;
    }

    /* Ensure images maintain aspect ratio */
    .image {
        height: 150px;
        overflow: hidden;
        position: relative;
    }

    /* Center-cropping */
    .image img {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        min-width: 100%;
        min-height: 100%;
        width: auto;
        height: auto;
    }

    /* Align title at the bottom of the card */
    .title {
        margin-top: auto;
    }
</style>

{% block content %}
<div class="container px-8 py-8 mx-auto">
    <div class="px-40 mx-4">
        <h1 class="text-3xl font-bold mb-4">My Services</h1>

        {% if messages %}
            {% for message in messages %}
                <div class="mt-4 px-8 py-4 bg-teal-200 text-teal-800">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="py-8">
            <a href="{% url 'add_service' %}" class="inline:block mt-4 px-8 py-4 text-white rounded-lg" style="background-color: #008080; transition: background-color 0.3s ease;" onmouseover="this.style.backgroundColor='#005757'" onmouseout="this.style.backgroundColor='#008080'">Add Service</a>
        </div>
    </div>

    <div class="content-container max-w-4xl mx-auto px-3">
        <div class="flex flex-wrap">
            {% for service in services %}
            <div class="service w-full sm:w-1/2 md:w-1/3 p-2">
                <div class="bg-gray-100 rounded-lg shadow-md hover:shadow-lg transition duration-300 h-full flex flex-col">
                    <a href="{% url 'service_detail' service.category.slug service.slug %}" class="block h-full">
                        <div class="image rounded-t-lg">
                            <img src="{{ service.get_thumbnail }}" alt="Image of {{ service.title }}" class="w-full h-full rounded-t-md">
                        </div>
                        <h2 class="p-3 text-lg font-semibold text-gray-800 title">{{ service.title }}</h2>
                        <p class="p-3"><strong>Status: </strong>{{ service.get_status_display }}</p>
                        <a href="{% url 'edit_service' service.pk %}" class="inline:block mt-2 px-2 py-2 text-white rounded-lg" style="background-color: #008080; transition: background-color 0.3s ease;" onmouseover="this.style.backgroundColor='#005757'" onmouseout="this.style.backgroundColor='#008080'">Edit</a>

                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    {% if services|length == 0 %}
        <p class="mt-4 py-4 px-8 bg-gray-200">You don't have any Services listed yet...</p>
    {% endif %}
</div>
{% endblock %}

userprofile/templates/userprofile/myaccount.html
{% extends 'base.html' %}

{% block title %}My Account{% endblock %}

{% block content %}
<div class="min-h-screen flex flex-col items-center px-4 py-20">
    <div class="w-full bg-white rounded-lg shadow-lg p-6">
        <h1 class="text-3xl font-bold mb-4">My Account</h1>

        <!-- Display Success or Error Messages -->
        <div id="messageContainer" class="mb-4" style="display: none;"></div>

        <!-- Display Username -->
        <p class="text-lg mb-4">Welcome, <strong>{{ request.user.username }}</strong></p>

        <!-- Edit Username Form (Initially Hidden) -->
        <form id="editUsernameForm" method="post" action="{% url 'edit_username' %}" style="display: none;">
            {% csrf_token %}
            <label for="id_username" class="block text-sm font-medium text-gray-700 mb-2">New Username:</label>
            <input type="text" id="id_username" name="username" value="{{ request.user.username }}"
                   class="mb-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-400 focus:ring focus:ring-teal-400 focus:ring-opacity-50">
            <button type="submit" class="py-2 px-4 bg-teal-600 text-white rounded-lg hover:bg-teal-700">Update</button>
        </form>

        <!-- Button to Toggle Edit Username Form -->
        <button id="editUsernameBtn" class="mt-4 py-2 px-4 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300">
            Edit Username
        </button>

        <!-- Edit Password Form (Initially Hidden) -->
        <form id="editPasswordForm" method="post" action="{% url 'change_password' %}" style="display: none;">
            {% csrf_token %}
            <label for="id_old_password" class="block text-sm font-medium text-gray-700 mb-2">Old Password:</label>
            <input type="password" id="id_old_password" name="old_password"
                   class="mb-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-400 focus:ring focus:ring-teal-400 focus:ring-opacity-50">

            <label for="id_new_password1" class="block text-sm font-medium text-gray-700 mb-2">New Password:</label>
            <input type="password" id="id_new_password1" name="new_password1"
                   class="mb-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-400 focus:ring focus:ring-teal-400 focus:ring-opacity-50">

            <label for="id_new_password2" class="block text-sm font-medium text-gray-700 mb-2">Confirm New Password:</label>
            <input type="password" id="id_new_password2" name="new_password2"
                   class="mb-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-400 focus:ring focus:ring-teal-400 focus:ring-opacity-50">

            <button type="submit" class="mt-4 py-2 px-4 bg-teal-600 text-white rounded-lg hover:bg-teal-700">Update Password</button>
        </form>

        <!-- Button to Toggle Edit Password Form -->
        <button id="editPasswordBtn" class="mt-4 py-2 px-4 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300">
            Edit Password
        </button>

        <!-- Apply for Vendor Button -->
        {% if not request.user.userprofile.is_vendor %}
        <form method="post" action="{% url 'apply_for_vendor' %}">
            {% csrf_token %}
            <button type="submit" class="inline:block mt-4 px-8 py-4 text-white rounded-lg" style="background-color: #008080; transition: background-color 0.3s ease;" onmouseover="this.style.backgroundColor='#005757'" onmouseout="this.style.backgroundColor='#008080'">Showcase Your Services</button>
        </form>
        {% endif %}

        <!-- Logout Button -->
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="inline:block mt-4 px-8 py-4 text-white rounded-lg bg-red-400 hover:bg-red-500">Log out</button>
        </form>

        <!-- Delete Account Button -->
        <form method="post" action="{% url 'delete_account' %}">
            {% csrf_token %}
            <button type="submit" class="mt-4 py-3 px-6 bg-red-400 text-white rounded-lg hover:bg-red-500">Delete Account</button>
        </form>

    </div>
</div>

<script>
    // JavaScript to toggle the visibility of the edit username form
    document.getElementById('editUsernameBtn').addEventListener('click', function() {
        var editUsernameForm = document.getElementById('editUsernameForm');
        if (editUsernameForm.style.display === 'none' || editUsernameForm.style.display === '') {
            editUsernameForm.style.display = 'block';
        } else {
            editUsernameForm.style.display = 'none';
        }
    });

    // JavaScript to toggle the visibility of the edit password form
    document.getElementById('editPasswordBtn').addEventListener('click', function() {
        var editPasswordForm = document.getElementById('editPasswordForm');
        if (editPasswordForm.style.display === 'none' || editPasswordForm.style.display === '') {
            editPasswordForm.style.display = 'block';
        } else {
            editPasswordForm.style.display = 'none';
        }
    });

    {% if messages %}
        var messageContainer = document.getElementById('messageContainer');
        messageContainer.style.display = 'block';
        {% for message in messages %}
            messageContainer.innerHTML += '<div class="text-sm py-1 px-2 {% if message.tags %}bg-{{ message.tags }}{% endif %}">{{ message }}</div>';
        {% endfor %}
    {% endif %}
</script>
{% endblock %}

userprofile/templates/userprofile/service_form.html
{% extends 'base.html' %}

{% block title %}Add service{% endblock %}

{% block content %}
<style>
    .form_content {
        padding: 15px;
        margin: 40px; /* Add margin around the entire content */
        border-radius: 10px; /* Add rounded corners */
        background-color: #f7f7f7; /* Add background color */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add box shadow for depth */
    }
</style>
<div class="form_content">
   <h1 class="text-2xl">{{ title }}</h1>

<form method='post' action="." enctype="multipart/form-data" class="space-y-5">
    {% csrf_token %}

    {{ form.as_p }}

    <button class="rounded-md mt-2 inline-block py-4 px-8 bg-teal-500 text-white hover:bg-teal-800">Submit</button>
</form>
{% if service %}
<a href="{% url 'delete_service' service.id %}" class="rounded-md mt-2 inline-block py-4 px-8 bg-red-500 text-white">Delete</a>
{% endif %}
</div>

{% endblock %}

userprofile/templates/userprofile/signup.html
{% extends 'base.html' %}
{% block title %}Signup{% endblock %}

{% block content %}
<div class="flex items-center justify-center my-5">
    <img src="\media\uploads\service_images\logo2.png" alt="Service Spotter Logo" class="h-8 mr-2">
    <h1 class="text-2xl font-bold">Service Spotter</h1>
</div>
<div class="max-w-md mx-auto mt-8 bg-white rounded-xl overflow-hidden shadow-md">
    <div class="py-4 px-6">
        <h1 class="text-2xl font-bold mb-4">Signup</h1>
        <form method="post" action=".">
            {% csrf_token %}

            {% if errors %}
                <div class="mb-4">
                    <p class="text-red-500">Please correct the following errors:</p>
                    <ul>
                        {% for error in errors.values %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <div class="mb-4">
                <label for="id_username" class="block text-sm font-medium text-gray-700">Username:</label>
                <input type="text" name="username" id="id_username" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring focus:ring-teal-500 focus:ring-opacity-50" required autofocus>
            </div>        

            
            <div class="mb-6">
                <label for="id_password" class="block text-sm font-medium text-gray-700">Password:</label>
                <input type="password" name="password1" id="id_password" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring focus:ring-teal-500 focus:ring-opacity-50" required>
            </div>

            <div class="mb-6">
                <label for="id_password2" class="block text-sm font-medium text-gray-700">Confirm Password:</label>
                <input type="password" name="password2" id="id_password2" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring focus:ring-teal-500 focus:ring-opacity-50" required>
            </div>

            <div class="mb-6 flex items-center">
                <label for="showPassword" class="flex-grow block text-sm font-medium text-gray-700">Show Passwords:</label>
                <div class="relative">
                    <input type="checkbox" id="showPassword" class="ml-2" onclick="togglePasswordVisibility()">
                </div>
            </div>
            


            <button type="submit" class="w-full py-2 px-4 bg-teal-600 text-white font-semibold rounded-xl hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-600 focus:ring-opacity-50">Sign up</button>
        </form>
    </div>
</div>
<script>
    function togglePasswordVisibility() {
        var passwordField = document.getElementById("id_password");
        var confirmPasswordField = document.getElementById("id_password2");

        if (passwordField.type === "password" && confirmPasswordField.type === "password") {
            passwordField.type = "text";
            confirmPasswordField.type = "text";
        } else {
            passwordField.type = "password";
            confirmPasswordField.type = "password";
        }
    }
</script>




{% endblock %}

userprofile/templates/userprofile/vendor_confirmation.html
{% extends 'base.html' %}

{% block title %}Confirm Service Listing{% endblock %}

{% block content %}
<div class="mt-8 max-w-md mx-auto bg-white rounded-xl overflow-hidden shadow-md p-6">
    <h1 class="text-2xl font-bold mb-4 text-center">Confirm Service Listing</h1>

    <form method="post" class="mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700">Are you sure you want to list your services here?</label>
            {% for choice in form.confirmation %}
                <label class="inline-flex items-center mt-2">
                    {{ choice.tag }}
                    <span class="ml-2 text-sm font-medium text-gray-700">{{ choice.choice_label }}</span>
                </label>
            {% endfor %}
        </div>

        <div class="flex justify-center">
            <button type="submit" class="w-full py-2 px-4 bg-teal-600 text-white font-semibold rounded-xl hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-600 focus:ring-opacity-50">Confirm</button>
        </div>
    </form>
</div>
{% endblock %}